import { Project } from '@/types';

export async function getProjects(): Promise<Project[]> {
  return [
    // --- MAIN PROJECTS ---
    {
      slug: 'cartera',
      title: 'Cartera',
      description: 'Production-grade, event-driven financial operating system & microservices platform for multi-wallet deposit allocations, mandate delegation, and double-entry ledger bookkeeping.',
      category: 'Enterprise Systems',
      techStack: ['Java 21', 'Spring Boot 3.3', 'Flutter', 'PostgreSQL', 'Apache Kafka', 'Redis', 'Docker', 'RazorpayX'],
      architectureTags: ['Microservices Architecture', 'Immutable Double-Entry Ledger', 'CASCADE CRDT Engine', 'CORTEX Resilience'],
      status: 'Production',
      githubUrl: 'https://github.com/omghante/cartera',
      demoUrl: 'https://cartera.dev',
      docsSlug: 'cartera',
      featured: true,
      outcome: 'Orchestrates 8 Spring Boot microservices with lock-free CASCADE CRDT balance calculations and selective REFLUX crash recovery.',
    },
    {
      slug: 'metapilot',
      title: 'MetaPilot',
      description: 'Production-grade multi-tenant WhatsApp marketing & CRM automation platform with bulk campaign broadcasting, real-time WebSocket inbox, and AI auto-reply chatbot.',
      category: 'Enterprise Systems',
      techStack: ['Django 5', 'Django REST Framework', 'Celery', 'Django Channels', 'Next.js', 'PostgreSQL 16', 'Redis 7', 'OpenRouter AI'],
      architectureTags: ['Multi-Tenant Middleware', 'Distributed Job Scheduler', 'Meta Graph API v22.0', 'Fernet AES-256 Encryption'],
      status: 'Production',
      githubUrl: 'https://github.com/omghante/metapilot',
      demoUrl: 'https://metapilot.dev',
      docsSlug: 'metapilot',
      blogSlug: 'scalable-whatsapp-graph-api',
      featured: true,
      outcome: 'Delivers asynchronous WhatsApp broadcast campaigns with token-bucket rate limiting and PostgreSQL row-level locking.',
    },
    {
      slug: 'patch-ai',
      title: 'Patch.ai',
      description: 'Autonomous software reliability & self-healing AI engine performing PyTorch GNN-driven Root Cause Analysis on runtime crash stack traces to generate safe patch proposals.',
      category: 'AI & ML',
      techStack: ['Python 3.10+', 'PyTorch', 'NetworkX', 'Graph Neural Networks', 'Click CLI', 'Watchdog', 'Hugging Face Hub'],
      architectureTags: ['PatchGNN Neural Network', 'Incident-Code Graph', 'Autonomous RCA', 'Live Telemetry Watcher'],
      status: 'Open Source',
      githubUrl: 'https://github.com/omghante/patch.ai',
      demoUrl: 'https://huggingface.co/om-ghante/patch-ai-v1',
      docsSlug: 'patch-ai',
      featured: true,
      outcome: 'Constructs incident-code graphs to diagnose runtime stack trace failures and propose automated self-healing patches.',
    },
    {
      slug: 'paper',
      title: 'Paper Ecosystem',
      description: 'Multi-repo Agentic AI & LLM Inference platform featuring a central gRPC token-streaming inference gateway (paper-core), real-time voice agent runtime (paper-caller), multi-agent tools, and MCP integrations.',
      category: 'AI & ML',
      techStack: ['Python 3.12', 'gRPC', 'Protobuf', 'FastAPI', 'MiniMax / OpenAI / Ollama', 'Docker', 'Prometheus'],
      architectureTags: ['gRPC Inference Gateway', 'Token Streaming', 'Multi-Agent Runtime', 'Model Context Protocol (MCP)'],
      status: 'Production',
      githubUrl: 'https://github.com/artificialpaper',
      demoUrl: 'https://github.com/artificialpaper',
      docsSlug: 'paper',
      featured: true,
      outcome: 'Abstracts multi-provider LLM inference (MiniMax, OpenAI, Ollama) behind a high-performance token-streaming gRPC gateway.',
    },
    {
      slug: 'reecall-ai',
      title: 'Reecall.ai',
      description: 'Neural Repository Memory Engine learning semantic file relationships in JS/TS codebases and retrieving engineering context via PyTorch GNN embeddings with zero hallucination.',
      category: 'AI & ML',
      techStack: ['Python 3.10+', 'PyTorch', 'Graph Neural Networks', 'NetworkX', 'torch.sparse', 'Click CLI', 'Hugging Face Hub'],
      architectureTags: ['Neural Repository Memory', 'Contrastive Loss', '32-dim File Embeddings', 'Structured Context JSON'],
      status: 'Open Source',
      githubUrl: 'https://github.com/omghante/reecall.ai',
      demoUrl: 'https://huggingface.co/omghante/reecall.ai',
      docsSlug: 'reecall-ai',
      featured: true,
      outcome: 'Learns semantic file-level relationships in JS/TS codebases and retrieves structured context with zero language hallucination.',
    },
    {
      slug: 'tide-os',
      title: 'Tide OS',
      description: 'Terminal Intelligence Development Engine (TIDE) — an AI coding harness for terminal developers shipped as a CLI and a bootable live Debian-based Linux ISO.',
      category: 'Developer Tools',
      techStack: ['TypeScript', 'Bun', 'Rust (N-API)', 'TUI', 'Debian Linux ISO', 'Model Context Protocol'],
      architectureTags: ['AI Coding Harness', 'Rust N-API Native Binding', 'Terminal UI (TUI)', 'Bootable Live Linux ISO'],
      status: 'Open Source',
      githubUrl: 'https://github.com/SnoozeScript/tide-os',
      docsSlug: 'tide-os',
      featured: true,
      outcome: 'Provides a multi-provider AI terminal coding harness with ~7.5k lines of Rust N-API native bindings for high-performance grep and embedded shell execution.',
    },

    // --- ALGORITHMS ---
    {
      slug: 'cascade-algorithm',
      title: 'CASCADE Algorithm',
      description: 'Vector-Clock CRDT Balance & Multi-Wallet Merging Engine guaranteeing lock-free, causal balance merges and zero overdraft preconditions.',
      category: 'Distributed Systems',
      techStack: ['Java 21', 'Vector Clocks', 'CRDT', 'Algorithms'],
      architectureTags: ['CRDT Vector Clock', 'Lock-Free Merges', 'Causal Consistency'],
      status: 'Open Source',
      githubUrl: "https://github.com/omghante/easy-blogs/tree/main/Amazon's%20SCOT%20and%20my%20CASCADE",
      featured: false,
      outcome: 'Replaces pessimistic database locks with lock-free causal balance calculation.',
    },
    {
      slug: 'cortex-algorithm',
      title: 'CORTEX Algorithm',
      description: 'Composite Pressure Score (CPS) Adaptive Resilience & Priority Request Shedding Engine preventing recovery storms under peak financial load.',
      category: 'Distributed Systems',
      techStack: ['Java 21', 'Algorithms', 'Resilience Design'],
      architectureTags: ['Composite Pressure Score', 'Priority Request Shedding', 'Adaptive Circuit Breaker'],
      status: 'Open Source',
      githubUrl: "https://github.com/omghante/easy-blogs/tree/main/Amazon's%20SCOT%20and%20my%20CORTEX",
      featured: false,
      outcome: 'Prevents cascading system failures during heavy transaction surges.',
    },
    {
      slug: 'rapid-algorithm',
      title: 'RAPID Algorithm',
      description: 'Constraint-propagation and branch & bound solver engine for multi-wallet deposit splitting across expense budgets, goals, and savings.',
      category: 'Distributed Systems',
      techStack: ['Java 21', 'Algorithms', 'Constraint Solver'],
      architectureTags: ['Constraint Propagation', 'Branch & Bound Solver', 'Multi-Wallet Allocation'],
      status: 'Open Source',
      githubUrl: "https://github.com/omghante/easy-blogs/tree/main/Amazon's%20SCOT%20and%20my%20RAPID",
      featured: false,
      outcome: 'Automatically allocates multi-wallet deposit inflows across budget constraint trees.',
    },
    {
      slug: 'reflux-algorithm',
      title: 'REFLUX Engine',
      description: 'Dependency-aware selective Kafka event replay engine executing application startup recovery and pruning dead intermediate writes.',
      category: 'Distributed Systems',
      techStack: ['Java 21', 'Apache Kafka', 'Algorithms'],
      architectureTags: ['Selective Event Replay', 'Crash Recovery', 'State Reconstruction'],
      status: 'Open Source',
      githubUrl: "https://github.com/omghante/easy-blogs/tree/main/Event%20Replay%20and%20my%20REFLUX",
      featured: false,
      outcome: 'Accelerated application startup crash recovery speed by ~47%.',
    },
    {
      slug: 'rollbackx-algorithm',
      title: 'ROLLBACKX Engine',
      description: 'Deployment health gate algorithm evaluating live metric thresholds (latency, error rate, heap) to trigger microservice rollbacks in under 60 seconds.',
      category: 'Distributed Systems',
      techStack: ['Java 21', 'DevOps Automation', 'Algorithms'],
      architectureTags: ['Deployment Health Gate', 'Canary Rollback', 'Automated Safety'],
      status: 'Open Source',
      githubUrl: "https://github.com/omghante/easy-blogs/tree/main/Deployment%20Safety%20and%20my%20ROLLBACKX",
      featured: false,
      outcome: 'Automates microservice canary deployment rollbacks within 60 seconds of anomaly detection.',
    },

    // --- NPM PACKAGES ---
    {
      slug: 'git-context',
      title: 'git-context (NPM Package)',
      description: 'Secure Node.js CLI tool (lexa) for managing multiple GitHub/GitLab accounts, credential-embedded cloning, per-folder identity configuration, and encrypted cloud profile sync.',
      category: 'Developer Tools',
      techStack: ['Node.js', 'JavaScript', 'Commander CLI', 'Inquirer', 'Firebase Auth', 'Firestore', 'AES-256-GCM'],
      architectureTags: ['Per-Folder Git Config', 'Credential-Embedded Clone', 'Firebase Cloud Sync', 'Natural Language Parser'],
      status: 'Open Source',
      githubUrl: 'https://github.com/omghante/git-context.npmpkg',
      demoUrl: 'https://www.npmjs.com/package/git-context',
      featured: true,
      outcome: 'Eliminates git credential prompts across multiple accounts using per-folder config isolation and encrypted profile sync.',
    },
    {
      slug: 'om-ghante-custom-components',
      title: 'om-ghante-custom-components (NPM Package)',
      description: 'Published React UI component library featuring reusable accessible buttons, inputs, modals, dropdowns, search bars, and layout primitives.',
      category: 'Developer Tools',
      techStack: ['React', 'JavaScript', 'Babel', 'npm'],
      architectureTags: ['Component Library', 'Design Primitives', 'NPM Package'],
      status: 'Open Source',
      githubUrl: 'https://github.com/omghante/custom-components.npmpkg',
      demoUrl: 'https://www.npmjs.com/package/om-ghante-custom-components',
      featured: false,
      outcome: 'Published modular component design system with 15+ UI primitives on NPM.',
    },
  ];
}

export async function getProjectBySlug(slug: string): Promise<Project | null> {
  const projects = await getProjects();
  return projects.find((p) => p.slug === slug) || null;
}
