import { Project } from '@/types';

export async function getProjects(): Promise<Project[]> {
  return [
    // --- MAIN PROJECTS ---
    {
      slug: 'cartera',
      title: 'Cartera',
      description: 'Distributed payment, mandate delegation, and ledger processing platform built for enterprise multi-wallet operations.',
      category: 'Enterprise Systems',
      techStack: ['Java', 'Spring Boot', 'Flutter', 'PostgreSQL', 'Docker', 'RazorpayX'],
      architectureTags: ['Distributed Ledger', 'Microservices', 'Mandate Processing'],
      status: 'Production',
      githubUrl: 'https://github.com/omghante/cartera',
      demoUrl: 'https://cartera.dev',
      docsSlug: 'cartera',
      featured: true,
      outcome: 'Processes multi-tenant wallet mandates with zero transaction drift.',
    },
    {
      slug: 'metapilot',
      title: 'MetaPilot',
      description: 'Enterprise integration platform orchestrating WhatsApp, Instagram, and Meta Ads APIs for automated marketing and lead workflows.',
      category: 'Enterprise Systems',
      techStack: ['Node.js', 'Express', 'Meta Graph API', 'Redis', 'BullMQ', 'PostgreSQL'],
      architectureTags: ['Microservices', 'Event-Driven Queue', 'OAuth 2.0 Token Refresh'],
      status: 'Production',
      githubUrl: 'https://github.com/omghante/metapilot',
      demoUrl: 'https://metapilot.dev',
      docsSlug: 'metapilot',
      blogSlug: 'scalable-whatsapp-graph-api',
      featured: true,
      outcome: 'Automated 50k+ daily outbound & inbound messages with under 120ms queue latency.',
    },
    {
      slug: 'paper',
      title: 'Paper Ecosystem',
      description: 'Agentic AI Ecosystem & Organization platform designed for autonomous multi-agent code generation and workflow orchestrations.',
      category: 'AI & ML',
      techStack: ['Python', 'FastAPI', 'Pytest', 'Poetry', 'LLM Agents', 'Docker'],
      architectureTags: ['Multi-Agent Architecture', 'Tool Execution Runtime', 'DAG Execution'],
      status: 'Production',
      githubUrl: 'https://github.com/artificialpaper/paper-core',
      demoUrl: 'https://github.com/artificialpaper',
      docsSlug: 'paper',
      featured: true,
      outcome: 'Orchestrates complex multi-step AI agent trajectories autonomously.',
    },
    {
      slug: 'reecall-ai',
      title: 'Reecall.ai',
      description: 'Conversational voice and context AI agent platform handling real-time customer query resolution and semantic context retrieval.',
      category: 'AI & ML',
      techStack: ['Python', 'Gemini API', 'FastAPI', 'Vector Store', 'WebSockets'],
      architectureTags: ['Voice AI Stream', 'Semantic Context Buffer', 'RAG Engine'],
      status: 'Production',
      githubUrl: 'https://github.com/omghante/reecall.ai',
      demoUrl: 'https://reecall.ai',
      featured: true,
      outcome: 'Resolves complex contextual user queries in under 300ms latency.',
    },
    {
      slug: 'tide-os',
      title: 'Tide OS',
      description: 'Developer Operating System and cloud container ecosystem providing lightweight sandbox environments and cloud infrastructure automation.',
      category: 'Developer Tools',
      techStack: ['Go', 'TypeScript', 'Docker', 'Kubernetes', 'gRPC'],
      architectureTags: ['Cloud OS Architecture', 'Container Sandboxing', 'Virtual File Systems'],
      status: 'In Development',
      githubUrl: 'https://github.com/omghante/tide-os',
      docsSlug: 'tide-os',
      featured: true,
      outcome: 'Provides isolated micro-VM sandboxes for cloud developer execution.',
    },

    // --- ALGORITHMS ---
    {
      slug: 'cascade-algorithm',
      title: 'Cascade Algorithm',
      description: 'High-throughput parallel task execution and dependency resolution algorithm designed for DAG-based execution pipelines.',
      category: 'Distributed Systems',
      techStack: ['TypeScript', 'Python', 'Algorithms'],
      architectureTags: ['DAG Resolver', 'Parallel Execution', 'Topological Sort'],
      status: 'Open Source',
      githubUrl: 'https://github.com/omghante/algorithms',
      featured: false,
      outcome: 'Optimized complex dependency resolution tree execution speed by 3.5x.',
    },
    {
      slug: 'cortex-algorithm',
      title: 'Cortex Algorithm',
      description: 'Context memory routing and semantic KV cache indexing algorithm optimized for LLM token window optimization.',
      category: 'AI & ML',
      techStack: ['Python', 'C++', 'Vector Indexing'],
      architectureTags: ['Cache Indexing', 'Context Pruning', 'Vector Hash Tree'],
      status: 'Open Source',
      githubUrl: 'https://github.com/omghante/algorithms',
      featured: false,
      outcome: 'Reduced LLM context payload sizes by 45% with zero recall loss.',
    },

    // --- NPM PACKAGES ---
    {
      slug: 'git-context',
      title: 'git-context (NPM Package)',
      description: 'High-performance Node.js CLI package for parsing and packaging full repository context into LLM-friendly formats.',
      category: 'Developer Tools',
      techStack: ['TypeScript', 'Node.js CLI', 'fs-extra', 'npm'],
      architectureTags: ['NPM Package', 'Gitignore Filtering', 'AST Context Tree'],
      status: 'Open Source',
      githubUrl: 'https://github.com/omghante/git-context',
      demoUrl: 'https://www.npmjs.com/package/git-context',
      blogSlug: 'building-llm-git-context-cli',
      featured: true,
      outcome: '1,000+ weekly downloads on NPM.',
    },
    {
      slug: 'om-ghante-custom-components',
      title: 'om-ghante-custom-components (NPM Package)',
      description: 'Reusable React & TypeScript UI component library featuring production-grade accessible components, badges, and layout primitives.',
      category: 'Developer Tools',
      techStack: ['React', 'TypeScript', 'Tailwind CSS', 'npm'],
      architectureTags: ['Component Library', 'Design Tokens', 'NPM Package'],
      status: 'Open Source',
      githubUrl: 'https://github.com/omghante/om-ghante-custom-components',
      demoUrl: 'https://www.npmjs.com/package/om-ghante-custom-components',
      featured: false,
      outcome: 'Published component design system used across enterprise projects.',
    },
  ];
}

export async function getProjectBySlug(slug: string): Promise<Project | null> {
  const projects = await getProjects();
  return projects.find((p) => p.slug === slug) || null;
}
